### ISSUE TITLE
Train 중 test를 할 때마다 jamo에서 문제가 있습니다. 

### ISSUE THREAD

**Issue by hyunR** [carpedm20/multi-speaker-tacotron-tensorflow#10]
Could not parse jamo: U+0

Exiting due to exception: Could not synthesize characters to Hangul.
Traceback (most recent call last):
  File "train.py", line 276, in train
    log_dir, step, loss, "train")
  File "train.py", line 112, in save_and_plot
    parallel_run(fn, items, parallel=False)
  File "multi-speaker-tacotron-tensorflow-master\utils\__init__.py", line 152, in parallel_run
    out = fn(item)
  File "train.py", line 97, in save_and_plot_fn
    skip_eos_and_pad=True, combine_jamo=True), isKorean=True)
  File "multi-speaker-tacotron-tensorflow-master\text\__init__.py", line 97, in sequence_to_text
    return jamo_to_korean(result)
  File "multi-speaker-tacotron-tensorflow-master\text\korean.py", line 64, in jamo_to_korean
    new_text += _get_text_from_candidates(candidates)
  File "multi-speaker-tacotron-tensorflow-master\text\korean.py", line 53, in _get_text_from_candidates
    return j2h(**dict(zip(["lead", "vowel", "tail"], candidates)))
  File "Python36\lib\site-packages\jamo\jamo.py", line 291, in j2h
    return jamo_to_hangul(lead, vowel, tail)
  File "Python36\lib\site-packages\jamo\jamo.py", line 278, in jamo_to_hangul
    '\x00')
jamo.jamo.InvalidJamoError: Could not synthesize characters to `Hangul.`

.wav 파일은 정상적으로 저장이 되는데, .png 파일을 만들때 문제가 생기는거 같습니다.
마지막  jamo_to_hangul(lead, vowel, tail)에서 잘못된 parameter가 들어가 생기는 문제라고 생각하는데,
직접적으로 .png파일을 만들려 시도해서 디버깅 할 수 있는 방법이 있을까요?

**Comment by k-enzy** [comment]
저 같은 경우는 FFmpeg 설치 다시하고 data폴더 지웠다가 getneration_data를 다시 실행 해서 해결 했습니다.

**Comment by YongWookHa** [comment]
@hyunR 혹시 문제 해결 하셨나요?

**Comment by hyedib** [comment]
@k-enzy @hyunR data 저도 똑같은 문제를 겪고 있습니다. 폴더를 지우는 건 dataset 폴더를 지우는 건가요? 그 후 다시 처음부터 데이터를 다운 받고 데이터를 generate하는 과정을 거쳐야하는 건가요? :)

**Comment by hyunR** [comment]
@hyedib 최근에 문제를 해결하게 되었는데 
`generate_data.py` 중 line 40을 `with open(config.metadata_path, encoding='utf-8') as f:` 처럼 엔코딩을 utf-8으로 json 파일을 저장하게 바꾸고 다시 원래있던 json 파일만 삭제하고 다시 만들었더니 문제가 해결되었습니다.
