### ISSUE TITLE
train을 할 수 없습니다

### ISSUE THREAD

**Issue by kdm1362** [carpedm20/multi-speaker-tacotron-tensorflow#11]
윈도우 아나콘다에서
python train.py --data_path=datasets/new 명령을 내리면

`Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from models import create_model, get_most_recent_checkpoint
  File "C:\Users\kdm\Desktop\multi-speaker-tacotron-tensorflow-master\models\__init__.py", line 3, in <module>
    from .tacotron import Tacotron
  File "C:\Users\kdm\Desktop\multi-speaker-tacotron-tensorflow-master\models\tacotron.py", line 13, in <module>
    from .rnn_wrappers import AttentionWrapper, DecoderPrenetWrapper, ConcatOutputAndAttentionWrapper
  File "C:\Users\kdm\Desktop\multi-speaker-tacotron-tensorflow-master\models\rnn_wrappers.py", line 5, in <module>
    from tensorflow.contrib.data.python.util import nest
ModuleNotFoundError: No module named 'tensorflow.contrib.data.python.util'`

가 뜨면서 진행이 되지 않습니다
python -m datasets.generate_data ./datasets/new/alignment.json 명령은 제대로 실행이 됐었습니다

제가 보기엔 원래 models 폴더에 create_model.py와 get_most_recent_checkpoint.py가 있어야 하는것
같던데 없더라고요 뭔가 해결 방법이 있나요?

아니면 저 두 파일은 더이상 배포하지 않는건가요?

**Comment by engiecat** [comment]
tensorflow 설치에 문제가 있거나 버전이 안맞는거 같습니다. 혹시 1.3.0으로 까셨는지요?

**Comment by kdm1362** [comment]
감사합니다 텐서플로우를 1.3.0으로 낮춰서 까니까 저 오류는 안나오네요

[WinError]2 파일을 찾을 수 없습니다 
같은 오류가 떠서 우분투로 시도해 보고 있습니다

**Comment by kdm1362** [comment]
이 오류는 어떻게 해결해야 하나요?

$ python3 train.py --data_path=datasets/new
 [*] MODEL dir: logs/new_2018-01-30_19-47-25
 [*] PARAM path: logs/new_2018-01-30_19-47-25/params.json
['datasets/new']
========================================
 [!] Detect non-krbook dataset. May need to set sampling rate from 22050 to 20000
========================================

['datasets/new']
fatal: Not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "train.py", line 336, in <module>
    main()
  File "train.py", line 332, in main
    train(config.model_dir, config)
  File "train.py", line 130, in train
    log(' [*] git recv-parse HEAD:\n%s' % get_git_revision_hash())
  File "/home/pebble/multi-speaker-tacotron-tensorflow-master/utils/__init__.py", line 191, in get_git_revision_hash
    return subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode("utf-8")
  File "/home/pebble/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/home/pebble/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.

git관련해서 뭔가를 더 해줘야 하나요?

**Comment by engiecat** [comment]
혹시 git clone으로 받으셨나요? 아니면 zip으로 받으셨나요? 후자로 받으셨으면 저런 오류가 발생할 수 있습니다.
사실 저 코드 자체는 코드에서 변경상황 띄워주는 거라 그냥 그거 주석먹이고 진행해도 될 것 같습니다.

**Comment by kdm1362** [comment]
학습도중에 종료시키는 방법이 따로 있나요? 
Ctrl+C로 인터럽트 시키니까

2018-01-31 18:00:14.417062: W tensorflow/core/kernels/queue_base.cc:295] _0_datafeeder/input_queue_1: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):

이후에 엄청난 에러들을 띄우다가 events.out.tfevents.1517389905.desktop
이런 파일만 남기고 종료 되어버렸습니다

컴퓨터가 구식이라 cpu로만 돌리니 스탭하나 넘기는데 40초가 걸리네요
나름 꾸준히 loss가 줄고있었는데 아쉽네요

**Comment by engiecat** [comment]
그거 1000 스텝마다 현재모델 저장하는게 기본인데 
train.py 옵션 보시면 그거 커맨드 라인에서 변경 가능해요

**Comment by itziana** [comment]
@kdm1362  님 위에 
[!] Detect non-krbook dataset. May need to set sampling rate from 22050 to 20000
 
이 오류 지금 저와 완전히 똑가은데 어떻게 해결하셨는지 알수 있나요?

**Comment by kdm1362** [comment]
혹시 한국어 음성을 학습 시키시려는 것이면  hparams.py의 11번째줄 `'cleaners': 'english_cleaners', #originally korean_cleaners` 을 바꾸어 주셨나요?

**Comment by itziana** [comment]
그건 영어로 하려고할때 현재 코리안 클리너스를 잉글리쉬 클리너스로 바꾸는거아닌가여 기본적으로 코리안으로 되있던데

**Comment by itziana** [comment]
저 이해 안가는게 하나가... 손석희 자료를 다운받아서 한글이랑 동영상에서 딴 목소리랑 학습을 시키잖아요
그런데 그다음에  python3 -m datasets.LJSpeech_1_0.prepare 이걸로 영어데이터셋은 왜 트레이닝 시키는건가요?
손석희...한글이면  python3 -m datasets.LJSpeech_1_0.prepare 이 과정은 건너뛰고 hparams.py 파일에 코리안 클리너스 부분만 수정해서 실행하면되는건지여

**Comment by itziana** [comment]
싱글스피커 모델이랑 다중스피커 모델이랑 차이가 뭘까여..

**Comment by engiecat** [comment]
@itziana 그건 LJSpeech 데이터셋의 텍스트 정보가 json 말고 다른 형식으로 되어있어서 그거 변환시켜준다고 넣은거에요. 
싱글스피커는 한 신경망 모델 당 한 목소리 멀티스피커는 한 신경망 모델 당 여러 목소리를 의미합니다.

**Comment by itziana** [comment]
@engiecat  친절한 설명 감사드립니다!

 저 기나긴 오류를 넘고넘어.. 여기까지 왔는데... 트레이닝 전 나오는 저 에러문구가 절 무척 불안하게합니다.. 제 CPU가 낮아서 진행이 어렵다는 이야기같은데, 컴퓨터를 바꿔야만 정상적인 진행이 가능한 부분인건지 알 수 있을까요

![image](https://user-images.githubusercontent.com/32944806/37383009-51e8517a-2789-11e8-877f-5698f13ae27c.png)

**Comment by rycont** [comment]
@itziana  은 이미 완성하셨거나 떠나셨거나 하셨겠지만 그거 그냥 무시해도 되는 메시지입니다!
