### ISSUE TITLE
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

### ISSUE THREAD

**Issue by kyewan10** [carpedm20/multi-speaker-tacotron-tensorflow#33]
학습을 하려고 하면 이런 오류가 떠서 진행이 안되네요

```
(MVoice) D:\MVoice\multi-speaker-tacotron-tensorflow-master>python train.py --data_path=datasets/Sample
 [*] MODEL dir: logs\Sample_2018-05-29_13-58-42
 [*] PARAM path: logs\Sample_2018-05-29_13-58-42\params.json
['datasets/Sample']
========================================
 [!] Detect non-krbook dataset. May need to set sampling rate from 22050 to 20000
========================================

Traceback (most recent call last):
  File "train.py", line 336, in <module>
    main()
  File "train.py", line 332, in main
    train(config.model_dir, config)
  File "train.py", line 130, in train
    log(' [*] git recv-parse HEAD:\n%s' % get_git_revision_hash())
  File "D:\MVoice\multi-speaker-tacotron-tensorflow-master\utils\__init__.py", line 191, in get_git_revision_hash
    return subprocess.check_output(['git', 'rev-parse', 'HEAD']).decode("utf-8")
  File "C:\Python\Python36\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다
```

뭐가 빠졌는지 알 수가 없으니 뭘 어떻게 질문해야될지도 모르겠네요..
numpy파일을 만든다는게 .npz파일을 만든다는건지
아니면 다른 학습데이터를 만든다는건지 몰라서 
이 과정의 어떤 환경적인 문제가 있는건지
전 단계에서 누락이 있었는지 전혀 모르겠네요...

참고로 OS는 윈도우10입니다.

**Comment by kyewan10** [comment]
자답입니다... 아래에도 같은 내용이 있었는데
제가 이해를 못했던 것 같네요
train.py에서 line130
`log(' [*] git recv-parse HEAD:\n%s' % get_git_revision_hash())`
을 주석처리하면 됩니다.
git관련 체크하는것 같은데 git에 연결을 안해놨거나 뭐 그런 이유같군요
