### ISSUE TITLE
datasets.generate_data ./datasets/음성이름/alignment.json이 전처리를 실행하지 못합니다 

### ISSUE THREAD

**Issue by rycont** [carpedm20/multi-speaker-tacotron-tensorflow#35]
![image](https://user-images.githubusercontent.com/35295182/41807705-bb9a6dc8-770d-11e8-8e47-0dd2ebbf3efa.png)

여기까지는 잘 진행되는가... 하다가도 금방 에러가 나네요

```
Traceback (most recent call last):
  File "D:\program\conda\envs\egoingSynthe\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\qkrwj\Downloads\multi-speaker-tacotron-tensorflow-master\datasets\generate_data.py", line 151, in _process_utterance
    wav = load_audio(audio_path)
  File "C:\Users\qkrwj\Downloads\multi-speaker-tacotron-tensorflow-master\audio\__init__.py", line 13, in load_audio
    audio = librosa.core.load(path, sr=hparams.sample_rate)[0]
  File "D:\program\conda\envs\egoingSynthe\lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "D:\program\conda\envs\egoingSynthe\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\program\conda\envs\egoingSynthe\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\program\conda\envs\egoingSynthe\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\qkrwj\Downloads\multi-speaker-tacotron-tensorflow-master\datasets\generate_data.py", line 191, in <module>
    build_from_path(config)
  File "C:\Users\qkrwj\Downloads\multi-speaker-tacotron-tensorflow-master\datasets\generate_data.py", line 101, in build_from_path
    n_frames = [future.result() for future in tqdm(futures)]
  File "C:\Users\qkrwj\Downloads\multi-speaker-tacotron-tensorflow-master\datasets\generate_data.py", line 101, in <listcomp>
    n_frames = [future.result() for future in tqdm(futures)]
  File "D:\program\conda\envs\egoingSynthe\lib\concurrent\futures\_base.py", line 432, in result
    return self.__get_result()
  File "D:\program\conda\envs\egoingSynthe\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
audioread.NoBackendError
```

generate_data.py의 101Line 내용은 n_frames = [n_frame for n_frame in n_frames if n_frame is not None]인데,  이 부분을 어떻게 수정해야할지 궁급합니다.

**Comment by rycont** [comment]
자답입니다. conda 가상환경에서는 환경변수로 ffmpeg가 인식이 되지 않아 `` conda install -c menpo ffmpeg ``로 해야됐었네요.
