### ISSUE TITLE
학습된 모델 다운로드에서 에러가 납니다.

### ISSUE THREAD

**Issue by Jeldo** [carpedm20/multi-speaker-tacotron-tensorflow#37]
우분투에서 기본적인 설치 진행은 문제 없이 끝났습니다.
이후 학습된 모델을 다운로드하려하는데 아래와 같은 오류가 발생합니다.

python3 download.py son 실행 시,

File "/usr/lib/python3.6/tarfile.py", line 1641, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1617, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1480, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.6/tarfile.py", line 2295, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.6/tarfile.py", line 1090, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.6/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.6/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.6/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.6/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\n<')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download.py", line 122, in <module>
    download_checkpoint('son')
  File "download.py", line 103, in download_checkpoint
    tar = tarfile.open(save_path, "r:gz")
  File "/usr/lib/python3.6/tarfile.py", line 1587, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.6/tarfile.py", line 1645, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file

이렇게 gzip 파일이 아니라고 나오는데,
어떻게 해결하는지 알 수 있을까요?

**Comment by kyewan10** [comment]
퍼블리시티권 침해 우려때문에 막아놨을거에요
이미 만들어진 모델은 포기하시고 음성데이터를 직접 만드셔야할듯...
