### ISSUE TITLE
음성제작 과정에서 ValueError: max() arg is an empty sequence 오류가 발생합니다.

### ISSUE THREAD

**Issue by crayonyak** [carpedm20/multi-speaker-tacotron-tensorflow#46]
안녕하세요. Train 이후, 음성을 만드는 과정에서 오류가 발생하고 있습니다.

운영체제 : Win10
Anaconda 사용 중입니다.

```
(base) C:\Users\user\Desktop\deep>python app.py --load_path logs/kim_2018-08-15_11-03-24 --num_speakers=1
C:\Users\user\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "app.py", line 129, in <module>
    synthesizer.load(config.load_path, config.num_speakers, config.checkpoint_step)
  File "C:\Users\user\Desktop\deep\synthesizer.py", line 33, in load
    checkpoint_path = get_most_recent_checkpoint(checkpoint_path, checkpoint_step)
  File "C:\Users\user\Desktop\deep\synthesizer.py", line 294, in get_most_recent_checkpoint
    max_idx = max(idxes)
ValueError: max() arg is an empty sequence
```

syntehsizer을 통해 특정 음성을 입력 후, 작동시켜도 동일한 오류가 발생하고 있습니다.

training까지 마친 상태에서, 이러한 오류가 발생하고 있는데, app.py 혹은 synthesizer.py에서 어떤 코드를 수정해야 될 지 모르겠습니다. 

조언주시면 감사하겠습니다.

**Comment by crayonyak** [comment]
죄송합니다. 가장 기본적인 실수를 했네요..
`python3 -m datasets.generate_data ./datasets/YOUR_DATASET/alignment.json`
가 먹히지 않았던 것을 까먹고 있었습니다.

https://github.com/carpedm20/multi-speaker-tacotron-tensorflow/issues/34

이 곳의 답변으로 해결하였습니다.

**Comment by hmmhmmhm** [comment]
아...... 저도 발생하네요 ㅠㅠ

**Comment by hmmhmmhm** [comment]
저는 이거 batch size 를 줄여서 해결했습니다. 제 경우엔 메모리가 부족한 상황인듯하더라고요, 그런데 학습은 되는데 이상하게 한마디도 말이 제대로 안 나오네요 ㅠ

**Comment by i2gor87** [comment]
_> 저는 이거 batch size 를 줄여서 해결했습니다. 제 경우엔 메모리가 부족한 상황인듯하더라고요, 그런데 학습은 되는데 이상하게 한마디도 말이 제대로 안 나오네요 ㅠ_
혹시 어느 파일을 수정하신 건가요? 저는 계속 찾아봐도 모르겠더라고요 ㅠ

**Comment by seolsnow** [comment]
ㅠ같은문제

**Comment by SeunggiMoon** [comment]
> _> 저는 이거 batch size 를 줄여서 해결했습니다. 제 경우엔 메모리가 부족한 상황인듯하더라고요, 그런데 학습은 되는데 이상하게 한마디도 말이 제대로 안 나오네요 ㅠ_
> 혹시 어느 파일을 수정하신 건가요? 저는 계속 찾아봐도 모르겠더라고요 ㅠ

hparams.py에서 'batch_size': 4 두고 하니 학습이 되긴 됩니다.
결과는 지켜봐야 하겠지만요..

**Comment by Marie0606** [comment]
hparams.py에 122번째 줄 보시면 'batch_size: 32'라고 되어있는데 16으로 바꿔보시면 됩니다.

**Comment by sts7184** [comment]
저같은 경우엔 ValueError: max() arg is an empty sequence 이 에러 난 이유가 음성이랑 json 파일로 학습한 npz 파일이 문제가 있어서 train.py 실행했을 때 data_feeder.py에 new_n_frame이 비어있어서 이런 오류가 발생했습니다. 인코딩 문제때문이었는데요 실제로 파이참에서 json 파일 열어보니까 글자가 다 깨져있더라고요. 그걸로 학습 데이터를 못 만들어서 리스트가 비어 있던것 같았습니다. 해결 방법은 json 파일 메모장으로 여서서 ANSI -> UTF-8로 인코딩 방법 수정해서 저장하고 다시 generate_data로 npz 만들고 제대로 된 npz가지고 train하니까 해결할 수 있었습니다.
