### ISSUE TITLE
학습 데이터 생성에서 cp949 오류가 발생합니다.

### ISSUE THREAD

**Issue by crayonyak** [carpedm20/multi-speaker-tacotron-tensorflow#47]
안녕하세요.

2.1.의 학습 데이터 생성을 위하여 `python3 -m datasets.generate_data ./datasets/아무개/alignment.json`
을 진행할 때, 다음과 같은 오류가 발생합니다.

```
(base) C:\Users\user\Desktop\deep>python -m datasets.generate_data ./datasets/kim/alignment.json

C:\Users\user\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
========================================
 [!] Sampling rate: 24000
========================================

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Desktop\deep\datasets\generate_data.py", line 191, in <module>
    build_from_path(config)
  File "C:\Users\user\Desktop\deep\datasets\generate_data.py", line 41, in build_from_path
    content = f.read()
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 36: illegal multibyte sequence
```

제 짧은 소견으로는 json에 한글이 들어가 있기때문에, 유니코드 오류가 난 것이라고 생각하는데, 제가 초보라서 어떻게 고쳐야할 지 잘 모르겠습니다. 도움 부탁드립니다.

(Window 10, Anaconda, tensorflow 1.3.0을 사용하고 있습니다.)

p.s. json을 생성할 때, Google API를 이용하지 않고, 제가 기존에 가지고 있던 자료를 활용하여 json을 직접 제작하였습니다. 그렇기때문에, json이 저장될 때 포맷이 문제가 되지 않았나 싶은데요.

json의 포맷을 바꿀 수 있는 방법이 따로 있을까요?

감사합니다.

**Comment by crayonyak** [comment]
메모장으로 오픈해서 유니코드만 변경하면 되는 문제였습니다... 해결했습니닷!

**Comment by hmmhmmhm** [comment]
감사합니다. 1년 뒤의 저에게 도움이 되었습니다.
