### ISSUE TITLE
alignment.json 에러

### ISSUE THREAD

**Issue by hansolc** [carpedm20/multi-speaker-tacotron-tensorflow#53]
안녕하세요 
python3 -m recognition.google --audio_pattern "./datasets/yuinna/audio/*.*.wav"
해당 명령어 까지 완성하여 

python3 -m recognition.alignment --recognition_path "./datasets/yuinna/recognition.json" --score_threshold=0.5 --recognition_encoding="utf-8"
까지 한 후 alignment.py  파일의 내용에서 encodig="utf-8"로 변경 해주었습니다.

gnition_encoding="utf-8"
align_text_batch:   0%|                                                                                                                                | 0/44003 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hs/project2/multi-speaker-tacotron-tensorflow/recognition/alignment.py", line 169, in <module>
    results = align_text_batch(config)
  File "/home/hs/project2/multi-speaker-tacotron-tensorflow/recognition/alignment.py", line 148, in align_text_batch
    desc="align_text_batch", parallel=False)
  File "/home/hs/project2/multi-speaker-tacotron-tensorflow/utils/__init__.py", line 152, in parallel_run
    out = fn(item)
  File "/home/hs/project2/multi-speaker-tacotron-tensorflow/recognition/alignment.py", line 106, in align_text_fn
    candidates = [strip_fn(line) for line in open(news_path, encoding='utf-8').readlines()]
FileNotFoundError: [Errno 2] No such file or directory: './datasets/yuinna/assets/20141106.txt'

저는 유인나의 목소리를 트레이닝 시킨 것을 test하고 싶어 해당 오류가 났습니다.
해당 오류는 /datasets/yuinna/alignment.py 파일에

{
    "./datasets/YOUR_DATASET/audio/001.mp3": "My name is Taehoon Kim.",
    "./datasets/YOUR_DATASET/audio/002.mp3": "The buses aren't the problem.",
    "./datasets/YOUR_DATASET/audio/003.mp3": "They have discovered a new particle.",
}

해당 형태와 같이 수동으로 작업을 해주어야 하나요?
아니면 따로 디렉토리 ./datasets/yuinna/assets/20141106.txt. 라는 형태로 파일을 만들어 주어야 하나요?

어떻게 오류를 해결하는지 여쭤보고 싶습니다..

**Comment by hs1003** [comment]
이 오류 어떻게 해결하신건가요?
