### ISSUE TITLE
datasets.generate_data ./datasets/son/alignment.json모델을 생성하는데서 부터 에러가 납니다.

### ISSUE THREAD

**Issue by lss9566** [carpedm20/multi-speaker-tacotron-tensorflow#54]
제가 기본 지식이 너무 부족하여 이 글과 한글로 된 글을 읽고 연습하고 있는데 너무 안되네요.
동영상도 두 번이나 반복해서 보고 이 글과 한글로 된 글도 읽었지만 제겐 너무나 어렵습니다.
우선 제가 한건 앵커브리핑에서 손석희 앵커목소리를  다섯시간 이상 분량을 따와서 mp3로 만들고 데이터셋에  오디오방에 넣어 놓았습니다. jason은 제가 어떻게 만드는지 몰라서 
{
    "./datasets/YOUR_DATASET/audio/001.mp3": "My name is Taehoon Kim.",
    "./datasets/YOUR_DATASET/audio/002.mp3": "The buses aren't the problem.",
    "./datasets/YOUR_DATASET/audio/003.mp3": "They have discovered a new particle.",
} 이런 식으로 비주얼스튜디오 코드에 붙혀 이름만 alignment.json로 만들었습니다. 텍스트 파일은 어떻게 하라는 건지 도대체 이해를 못하여 못넣었습니다. 아마 이부분이 에러의 요인 같습니다만 ㅠㅠ 제겐 너무 어렵네여....
시간이 걸려도 좋으니 제게 설명만 해 주실 수 있으신 분이 있으면 정말 감사드리겠습니다..... 

(tensorflow) iseungsun-ui-iMac:multi iseungsun$ python3 -m datasets.generate_data ./datasets/son/alignment.json
========================================
 [!] Sampling rate: 22050
========================================

Traceback (most recent call last):
  File "/Users/iseungsun/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/iseungsun/anaconda3/envs/tensorflow/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/iseungsun/Downloads/multi/datasets/generate_data.py", line 191, in <module>
    build_from_path(config)
  File "/Users/iseungsun/Downloads/multi/datasets/generate_data.py", line 42, in build_from_path
    info = json.loads(content)
  File "/Users/iseungsun/anaconda3/envs/tensorflow/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/iseungsun/anaconda3/envs/tensorflow/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/iseungsun/anaconda3/envs/tensorflow/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 237)
이 메세지만 줄기차게 뜨고 진행이 안됩니다. 답답하네여..... 밑의 댓글들을 다 읽어 보고 연습하고 있는데도 안됩니다.

**Comment by wodnd999999** [comment]
{
"./datasets/YOUR_DATASET/audio/001.mp3": "My name is Taehoon Kim.",
"./datasets/YOUR_DATASET/audio/002.mp3": "The buses aren't the problem.",
"./datasets/YOUR_DATASET/audio/003.mp3": "They have discovered a new particle.",
}
에서 마지막 괄호 바로 앞에 콤마는 제거해주셔야 됩니다.

오류의 마지막 줄
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 237)
은 콤마가 나왔으니까 다음에 뭔가 또 다른게 나오겠구나 했는데 예상치 못한 문자 } 가 와서 나온 에러입니다.

**Comment by lss9566** [comment]
p{margin-top:0;margin-bottom:0}
    


    이제 봤습니다. ㅠㅠ 정말 감사드립니다.   고맙습니다. 최재웅님
--------- 원본 메일 ---------

    
        보낸사람: 최재웅 <notifications@github.com>
        받는사람: carpedm20/multi-speaker-tacotron-tensorflow <multi-speaker-tacotron-tensorflow@noreply.github.com>
        
            참조: lss9566 <lss9566@hanmail.net>, Author <author@noreply.github.com>
        
        날짜: 18.10.25 20:59 GMT +0900
        제목: Re: [carpedm20/multi-speaker-tacotron-tensorflow] datasets.generate_data ./datasets/son/alignment.json모델을 생성하는데서 부터 에러가 납니다. (#54)
        
        
    
    
        {
"./datasets/YOUR_DATASET/audio/001.mp3": "My name is Taehoon Kim.",
"./datasets/YOUR_DATASET/audio/002.mp3": "The buses aren't the problem.",
"./datasets/YOUR_DATASET/audio/003.mp3": "They have discovered a new particle.",
}
에서 마지막 괄호 바로 앞에 콤마는 제거해주셔야 됩니다.
오류의 마지막 줄
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 237)
은 콤마가 나왔으니까 다음에 뭔가 또 다른게 나오겠구나 했는데 예상치 못한 문자 } 가 와서 나온 에러입니다.
