### ISSUE TITLE
Deepvoice training

### ISSUE THREAD

**Issue by hansolc** [carpedm20/multi-speaker-tacotron-tensorflow#57]
현재 single모델로 손석희 모델은 트레이닝을 성공한 상태 이구요
제가 다른 음성 데이터가 적어서 손석희 데이터를 통해 다른 목소리로 트레이닝을 해보려고  deepvoice 로 훈련을
시켰는데 step은 진행 되지만 synthesizer.py 을 통해 음성을 만드는 부분에서 알 수 없는 오류가 나와 질문 드립니다.

Constructing model: tacotron
UPDATE model_type: single -> deepvoice
Traceback (most recent call last):
  File "synthesizer.py", line 383, in <module>
    synthesizer.load(config.load_path, config.num_speakers, config.checkpoint_step)
  File "synthesizer.py", line 52, in load
    self.num_speakers, speaker_id)
  File "/home/hs/jongsul/multi-speaker-tacotron-tensorflow/models/tacotron.py", line 189, in initialize
    for idx, cell in enumerate(decoder_rnn_init_states):
TypeError: 'NoneType' object is not iterable

이와 같이 데이터가 없다고 나오는데 왜그런지 알 수 있을까요??

**Comment by freds0** [comment]
Try passing the parameter  --num_speakers=2 to the synthesizer.py script. It works for me.
