### ISSUE TITLE
generate_data.py 실행시 ValueError 발생 문제입니다.

### ISSUE THREAD

**Issue by topkcaj49** [carpedm20/multi-speaker-tacotron-tensorflow#61]
python -m datasets.generate_data ./datasets/son/alignment.json 를 실행시키면 나오는 에러입니다. 다른건 issue에서 글을 찾아보고 인터넷 검색을 해서 해결해왔는데, 이건 도무지 감이 잡히지 않습니다. 괜찮으시면 해결방법을 얻어갈 수 있을까요?

그리고 저 하단 에러항목인 n_frame은 어디에 사용되는건가요..?

--------------------------------------------Error Traceback 항목------------------------------------------------

Traceback (most recent call last):
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\datasets\generate_data.py", line 154, in _process_utterance
    mel_spectrogram = melspectrogram(wav).astype(np.float32)
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\audio\__init__.py", line 66, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D)))
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\audio\__init__.py", line 133, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\audio\__init__.py", line 144, in _build_mel_basis
    return librosa.filters.mel(hparams.sample_rate, n_fft, n_mels=hparams.num_mels)
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\site-packages\librosa\filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\datasets\generate_data.py", line 191, in <module>
    build_from_path(config)
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\datasets\generate_data.py", line 101, in build_from_path
    n_frames = [future.result() for future in tqdm(futures)]
  File "C:\Users\DAVE_HOME\Desktop\Deep Voice\datasets\generate_data.py", line 101, in <listcomp>
    n_frames = [future.result() for future in tqdm(futures)]
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\DAVE_HOME\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)

**Comment by junpa** [comment]
아마 모듈 버전을 낮춰서 해결한걸로 기억하는데 
librosa였던거같습니다.

**Comment by topkcaj49** [comment]
librosa 기존 버전은 0.5.1 이었습니다.
0.4.3으로 변경하니 잘 작동이 됩니다! 감사합니다!

**Comment by hmmhmmhm** [comment]
감사합니다. 나중에 도움이 되었습니다.
