### ISSUE TITLE
윈도우 10 아나콘다에서 돌리는데 오류

### ISSUE THREAD

**Issue by BlueDragon20148** [carpedm20/multi-speaker-tacotron-tensorflow#70]
Generated 32 batches of size 32 in 11.368 sec
Step 500     [16.855 sec/step, loss=0.14942, avg_loss=0.15335]
Writing summary at step: 500
Saving audio and alignment...
  0%|                                                                                            | 0/1 [00:06<?, ?it/s]
Exiting due to exception: data must be floating-point
Traceback (most recent call last):
  File "train.py", line 268, in train
    log_dir, step, loss, "train")
  File "train.py", line 104, in save_and_plot
    parallel_run(fn, items, parallel=False)
  File "D:\multi-speaker-tacotron-tensorflow\utils\__init__.py", line 151, in parallel_run
    out = fn(item)
  File "train.py", line 89, in save_and_plot_fn
    save_audio(waveform, audio_path)
  File "D:\multi-speaker-tacotron-tensorflow\audio\__init__.py", line 25, in save_audio
    hparams.sample_rate if sample_rate is None else sample_rate)
  File "<C:\Users\USER\Anaconda3\lib\site-packages\decorator.py:decorator-gen-6>", line 2, in write_wav
  File "C:\Users\USER\Anaconda3\lib\site-packages\librosa\util\decorators.py", line 58, in __wrapper
    return func(*args, **kwargs)
  File "C:\Users\USER\Anaconda3\lib\site-packages\librosa\output.py", line 239, in write_wav
    util.valid_audio(y, mono=False)
  File "C:\Users\USER\Anaconda3\lib\site-packages\librosa\util\utils.py", line 160, in valid_audio
    raise ParameterError('data must be floating-point')
librosa.util.exceptions.ParameterError: data must be floating-point
2019-10-09 23:07:55.804218: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\kernels\queue_base.cc:295] _1_datafeeder/input_queue: Skipping cancelled enqueue attempt with queue not closed
2019-10-09 23:07:55.815882: W C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\36\tensorflow\core\kernels\queue_base.cc:295] _0_datafeeder/input_queue_1: Skipping cancelled enqueue attempt with queue not closed
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1327, in _do_call
    return fn(*args)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1306, in _run_fn
    status, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
  File "C:\Users\USER\Anaconda3\lib\contextlib.py", line 88, in __exit__
    next(self.gen)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_1_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue_1, _arg_datafeeder/inputs_1_0_1, _arg_datafeeder/input_lengths_1_0_0, _arg_datafeeder/loss_coeff_1_0_3, _arg_datafeeder/mel_targets_1_0_4, _arg_datafeeder/linear_targets_1_0_2)]]
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/loss_coeff_0_3, _arg_datafeeder/mel_targets_0_4, _arg_datafeeder/linear_targets_0_2)]]

During handling of the above exception, another exception occurred:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 204, in run
    self._enqueue_next_group()
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 204, in run
    self._enqueue_next_group()
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 242, in _enqueue_next_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 242, in _enqueue_next_group
    self._session.run(self._enqueue_op, feed_dict=feed_dict)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 895, in run
    run_metadata_ptr)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1321, in _do_run
    options, run_metadata)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/loss_coeff_0_3, _arg_datafeeder/mel_targets_0_4, _arg_datafeeder/linear_targets_0_2)]]

Caused by op 'datafeeder/input_queue_enqueue', defined at:
  File "train.py", line 322, in <module>
    main()
  File "train.py", line 318, in main
    train(config.model_dir, config)
  File "train.py", line 136, in train
    data_type='train', batch_size=hparams.batch_size)
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 160, in __init__
    self._enqueue_op = queue.enqueue(self._placeholders)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 321, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1587, in _queue_enqueue_v2
    name=name)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue, _arg_datafeeder/inputs_0_1, _arg_datafeeder/input_lengths_0_0, _arg_datafeeder/loss_coeff_0_3, _arg_datafeeder/mel_targets_0_4, _arg_datafeeder/linear_targets_0_2)]]

tensorflow.python.framework.errors_impl.CancelledError: Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_1_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue_1, _arg_datafeeder/inputs_1_0_1, _arg_datafeeder/input_lengths_1_0_0, _arg_datafeeder/loss_coeff_1_0_3, _arg_datafeeder/mel_targets_1_0_4, _arg_datafeeder/linear_targets_1_0_2)]]

Caused by op 'datafeeder/input_queue_1_enqueue', defined at:
  File "train.py", line 322, in <module>
    main()
  File "train.py", line 318, in main
    train(config.model_dir, config)
  File "train.py", line 139, in train
    data_type='test', batch_size=config.num_test)
  File "D:\multi-speaker-tacotron-tensorflow\datasets\datafeeder.py", line 160, in __init__
    self._enqueue_op = queue.enqueue(self._placeholders)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 321, in enqueue
    self._queue_ref, vals, name=scope)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1587, in _queue_enqueue_v2
    name=name)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\Users\USER\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

CancelledError (see above for traceback): Enqueue operation was cancelled
         [[Node: datafeeder/input_queue_1_enqueue = QueueEnqueueV2[Tcomponents=[DT_INT32, DT_INT32, DT_FLOAT, DT_FLOAT, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](datafeeder/input_queue_1, _arg_datafeeder/inputs_1_0_1, _arg_datafeeder/input_lengths_1_0_0, _arg_datafeeder/loss_coeff_1_0_3, _arg_datafeeder/mel_targets_1_0_4, _arg_datafeeder/linear_targets_1_0_2)]]

이런 식으로 떠서 하...

**Comment by BlueDragon20148** [comment]
아 librosa버전을 0.5.1로 바꾸니까 해결 됐습니다.
