### ISSUE TITLE
datasets.generate_data 에러

### ISSUE THREAD

**Issue by froglike6** [carpedm20/multi-speaker-tacotron-tensorflow#77]
Traceback (most recent call last):
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/root/ttsproject/datasets/generate_data.py", line 154, in _process_utterance
    mel_spectrogram = melspectrogram(wav).astype(np.float32)
  File "/root/ttsproject/audio/__init__.py", line 66, in melspectrogram
    S = _amp_to_db(_linear_to_mel(np.abs(D)))
  File "/root/ttsproject/audio/__init__.py", line 133, in _linear_to_mel
    _mel_basis = _build_mel_basis()
  File "/root/ttsproject/audio/__init__.py", line 144, in _build_mel_basis
    return librosa.filters.mel(hparams.sample_rate, n_fft, n_mels=hparams.num_mels)
  File "/usr/local/lib/python3.6/site-packages/librosa/filters.py", line 247, in mel
    lower = -ramps[i] / fdiff[i]
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/ttsproject/datasets/generate_data.py", line 191, in <module>
    build_from_path(config)
  File "/root/ttsproject/datasets/generate_data.py", line 101, in build_from_path
    n_frames = [future.result() for future in tqdm(futures)]
  File "/root/ttsproject/datasets/generate_data.py", line 101, in <listcomp>
    n_frames = [future.result() for future in tqdm(futures)]
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (1,1025) (0,)

위와 같이 뜨면서 에러가 뜹니다.

**Comment by quhb2455** [comment]
해결 하셨나요?
