### ISSUE TITLE
 문장 예측 도중 오류가 발생합니다

### ISSUE THREAD

**Issue by ghkimwoo** [carpedm20/multi-speaker-tacotron-tensorflow#81]
By using Google Speech Recognition API, we predict sentences for all segmented audios. 의 python3 -m recognition.google --audio_pattern "./datasets/son/audio/*.*.wav" 를 수행하던 도중 다음과 같은 오류가 발생합니다.

**Comment by ghkimwoo** [comment]
[*] Audio saved: ./datasets/son/audio/NB10584578.0000.tmp.wav
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/retry.py", line 121, in inner
    return to_call(*args)
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/grpc/_channel.py", line 484, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/home/username/.local/lib/python3.6/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/recognition/google.py", line 61, in text_recognition
    response = client.recognize(config, audio)
  File "/home/username/.local/lib/python3.6/site-packages/google/cloud/gapic/speech/v1/speech_client.py", line 201, in recognize
    return self._recognize(request, options)
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/home/username/.local/lib/python3.6/site-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
google.gax.errors.RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.)>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/username/recognition/google.py", line 73, in text_recognition
    raise Exception("OS error: {0}".format(err))
Exception: OS error: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.)>)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/username/recognition/google.py", line 119, in <module>
    results = text_recognition_batch(paths, config)
  File "/home/username/recognition/google.py", line 96, in text_recognition_batch
    desc="text_recognition_batch", parallel=True)
  File "/home/username/utils/__init__.py", line 147, in parallel_run
    fn, items), total=len(items), desc=desc):
  File "/home/username/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
Exception: OS error: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.PERMISSION_DENIED, Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.)>)

**Comment by solalala-12** [comment]
api 키 발급 하셨나요 ?

**Comment by ghkimwoo** [comment]
서비스 계정의 키 만들기라면 발급했습니다만..  혹시 gcloud init로 설정할때마다 발급해야하나요?

**Comment by solalala-12** [comment]
저같은 경우 리눅스 환경에서 작업했는데 export로 키 등록해놓으니 문제없이 잘 작동했습니다.

**Comment by ghkimwoo** [comment]
아 서비스계정을 등록하지 않고 있던 걸로 해서 생긴 일이었던것 같습니다. + export도 같이 완료해서 해결되었습니다. 감사합니다!
