### ISSUE TITLE
Google Speech Recognition API 를 사용하여 모든 세그먼트 오디오에 대한 문장을 예측합니다. 중 오류

### ISSUE THREAD

**Issue by ghkimwoo** [carpedm20/multi-speaker-tacotron-tensorflow#82]
sudo python3 -m recognition.google --audio_pattern "./datasets/son/audio/*.*.wav" 중 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/bsu4696123/recognition/google.py", line 73, in text_recognition
    raise Exception("OS error: {0}".format(err))
Exception: OS error: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in g
cloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/."
        debug_error_string = "{"created":"@1591183496.775877978","description":"Error received from peer ipv4:216.58.196.234:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Your application has authenticated using end 
user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_se
rvice_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.","grpc_status":7}"
>)
"""
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/(username)/recognition/google.py", line 119, in <module>
    results = text_recognition_batch(paths, config)
  File "/home/(username)/recognition/google.py", line 96, in text_recognition_batch
    desc="text_recognition_batch", parallel=True)
  File "/home/(username)/utils/__init__.py", line 147, in parallel_run
    fn, items), total=len(items), desc=desc):
  File "/home/(username)/.local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
Exception: OS error: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "Your application has authenticated using end user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in g
cloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/."
        debug_error_string = "{"created":"@1591183496.775877978","description":"Error received from peer ipv4:***.***.***.***:443","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Your application has authenticated using end 
user credentials from the Google Cloud SDK or Google Cloud Shell which are not supported by the speech.googleapis.com. We recommend configuring the billing/quota_project setting in gcloud or using a service account through the auth/impersonate_service_account setting. For more information about service accounts and how to use them in your application, see https://cloud.google.com/docs/authentication/.","grpc_status":7}"
>) 라고 오류가 나는데 어떻게 해야 하나요..

**Comment by solalala-12** [comment]
API 발급받고 키 다운로드 받으셨나요 ?

**Comment by ghkimwoo** [comment]
> API 발급 받고 암호 화폐 다운로드 받았나요?
서비스계정에서 Json 키를 받고 cp로 우분투에 넘겼습니다만... 그래도 오류가 납니다
