### ISSUE TITLE
invalid token 오류

### ISSUE THREAD

**Issue by GwanghyeonBaek** [carpedm20/multi-speaker-tacotron-tensorflow#87]
python -m recognition.alignment --recognition_path "./datasets/son/recognition.json" --score_threshold=0.5

이 코드를 입력 후 list index out of range 오류가 떠서 recognition.json에서 하기 텍스트를 삭제하였습니다.
NB11653121 
NB11663681 
NB11684780 
NB11702006 
NB11722589 
NB11740377 
NB11771397

그랬더니 이제는 이러한 오류가 뜨네요 해결방법이 있을까요?
Traceback (most recent call last):
  File "C:\Users\bgh93\.conda\envs\voice\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\bgh93\.conda\envs\voice\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\다운로드\git_hub\multi-Speaker-tacotron-tensorflow\recognition\alignment.py", line 172, in <module>
    results = align_text_batch(config)
  File "D:\다운로드\git_hub\multi-Speaker-tacotron-tensorflow\recognition\alignment.py", line 151, in align_text_batch
    desc="align_text_batch", parallel=True)
  File "D:\다운로드\git_hub\multi-Speaker-tacotron-tensorflow\utils\__init__.py", line 147, in parallel_run
    fn, items), total=len(items), desc=desc):
  File "C:\Users\bgh93\.conda\envs\voice\lib\site-packages\tqdm\_tqdm.py", line 949, in __iter__
    for obj in iterable:
  File "C:\Users\bgh93\.conda\envs\voice\lib\multiprocessing\pool.py", line 735, in next
    raise value
  File "<unknown>", line 1
    -08
      ^

**Comment by quhb2455** [comment]
NB11653121
NB11663681
NB11684780
NB11702006
NB11722589
NB11740377
NB11771397
NB11848150
NB11899283

dataset update로 인해.. 
위의 9개의 data를 지워주셔야 error 없이 진행 가능합니다.

**Comment by quhb2455** [comment]
invalid token 오류는 
NB111678190.txt에 보면
>관련 리포트보러가기"EGR 열 충격 파손 위험" BMW는 2016년부터 알고 있었다박소연 기자 / 2018-08-08 20:16더구나 이에 대한 문제의 가능성은 이미 2년 전부터 파악했던 것으로 알려졌죠. 

1개의 문장(혹은 라인)이 이런식으로 구성되어 있을 수 있는데,
이때 "~ / 2018-08-08더구나..~" 이부분에서 오류가 발생 하는 것입니다.

위 문장의 앞 부분
관련 리포트보러가기"EGR 열 충격 파손 위험" BMW는 2016년부터 알고 있었다박소연 기자 / 2018-08-08 20:16 << 을 삭제하고
더구나 이에 대한 문제의 가능성은 이미 2년 전부터 파악했던 것으로 알려졌죠.  << 로 바꿔주시면됩니다.
